---
definitions:

resources:
  - icon: github
    name: govuk-infrastructure
    source:
      branch: main
      uri: https://github.com/alphagov/govuk-infrastructure
    type: git

groups:
  - name: all
    jobs:
      - update-pipeline
      - deploy-monitoring
      - configure-grafana

  - name: monitoring
    jobs:
      - deploy-monitoring
      - configure-grafana

  - name: admin
    jobs:
      - update-pipeline

jobs:
  - name: update-pipeline
    plan:
    - get: govuk-infrastructure
      trigger: true
    - file: govuk-infrastructure/concourse/pipelines/monitoring.yml
      set_pipeline: monitoring

  - name: deploy-monitoring
    plan:
    - get: govuk-infrastructure
      passed:
      - update-pipeline
      trigger: true
    - task: terraform-apply
      config:
        inputs:
        - name: govuk-infrastructure
        params:
          AWS_REGION: eu-west-1
          ASSUME_ROLE_ARN: 'arn:aws:iam::430354129336:role/govuk-concourse-deployer'
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: hashicorp/terraform
            tag: 0.14.6
            username: ((docker_hub_username))
            password: ((docker_hub_authtoken))
        run:
          dir: govuk-infrastructure/terraform/deployments/monitoring/infra
          path: sh
          args:
          - '-c'
          - |
            set -eu

            terraform init -backend-config "role_arn=$ASSUME_ROLE_ARN"
            terraform apply \
              -var "assume_role_arn=$ASSUME_ROLE_ARN" \
              -var-file ../../variables/common.tfvars \
              -var-file ../../variables/test/common.tfvars \
              -auto-approve

  - name: configure-grafana
    plan:
    - get: govuk-infrastructure
      passed:
      - deploy-monitoring
      trigger: true
    - task: terraform-apply
      config:
        inputs:
        - name: govuk-infrastructure
          path: src
        params:
          AWS_REGION: eu-west-1
          ASSUME_ROLE_ARN: 'arn:aws:iam::430354129336:role/govuk-concourse-deployer'
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: hashicorp/terraform
            tag: 0.14.6
            username: ((docker_hub_username))
            password: ((docker_hub_authtoken))
        run:
          path: sh
          args:
          - '-c'
          - |
            set -eu

            root_dir=$(pwd)

            APP_DIR="${root_dir}/src/terraform/deployments/monitoring/grafana"
            cd ${APP_DIR}

            terraform_apply() {
              terraform apply -var "assume_role_arn=$ASSUME_ROLE_ARN" -auto-approve
            }

            terraform init -backend-config "role_arn=$ASSUME_ROLE_ARN"

            if ! terraform_apply; then
                # See bug https://github.com/grafana/terraform-provider-grafana/issues/129
                # where terraform does not recreate some grafana resources if not found

                echo "fixing terraform state bug by removing state"
                terraform state rm module.grafana-app-config.grafana_data_source.cloudwatch

                echo "applying terraform again"
                terraform_apply
            fi
