platform: linux
image_resource:
  type: docker-image
  source:
    repository: govuk/ecs-cli
    tag: latest
    username: ((docker_hub_username))
    password: ((docker_hub_authtoken))
inputs:
  - name: govuk-infrastructure
  - name: src
params:
  AWS_REGION: eu-west-1
  ASSUME_ROLE_ARN:
  SOURCE_PATH: src
  S3_BUCKET_PATH_PATTERN:
  WORKSPACE:
run:
  path: ./govuk-infrastructure/concourse/tasks/push-dir-to-s3.sh
