name: Ruby linting and tests
on:
  push:
    paths:
    - .github/workflows/ci-ruby.yml
    - '**/*.rake'
    - '**/*.rb'
    - '**/*.rspec'
    - '**/.rubocop.yml'
    - '**/.ruby-version'
    - '**/Gemfile'
    - '**/Rakefile'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - run: bundle install
      - run: rubocop
      - run: rspec
