name: linting
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: terraform fmt
        working-directory: terraform
        run: |
          brew install tfenv
          tfenv install
          if ! terraform fmt -write=false -diff=true -list=true -recursive -check .
          then
            >&2 echo "Some terraform files weren't formatted correctly. Run 'terraform fmt' to fix them."
          fi

