# USAGE
# -----
#
# on:
#   workflow_dispatch:
#     branches:
#       - main
#   push:
#     branches:
#       - main
#     paths-ignore:
#       - "Jenkinsfile"
#       - ".git**"
#
# jobs:
#   deploy-to-eks:
#     uses: alphagov/govuk-infrastructure/.github/workflows/deploy.yaml@main
#     secrets:
#       WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
#       WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
#       GOVUK_CI_GITHUB_API_TOKEN: ${{ secrets.GOVUK_CI_GITHUB_API_TOKEN }}
#
# REUSABLE WORKFLOW
# -----------------

name: Deploy

on:
  workflow_call:
    inputs:
      imageTag:
        description: 'An image tag to deploy'
        required: false
        default: ${{ github.sha }}
        type: string
      manualDeploy:
        description: 'Whether it is a manual deployment'
        required: false
        default: "false"
        type: string
      appName:
        description: 'Name of the app being deployed'
        required: false
        default: ${{ github.event.repository.name }}
        type: string
    secrets:
      WEBHOOK_TOKEN:
        required: true
      WEBHOOK_URL:
        required: true
      GOVUK_CI_GITHUB_API_TOKEN:
        required: true

jobs:
  update-image-tag:
    name: Update image tag
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        env:
          ENVIRONMENT: integration
          IMAGE_TAG: ${{ inputs.imageTag }}
          REPO_NAME: ${{ inputs.appName }}
          MANUAL_DEPLOY: ${{ inputs.manualDeploy }}
          WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GOVUK_CI_GITHUB_API_TOKEN }}
        run: |
          # Check actor has permission to deploy
          DEPLOY_TEAM_MEMBERSHIP=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/orgs/alphagov/teams/gov-uk-production-deploy/memberships/${{ github.actor }} | jq -r '.state')

          if [[ "${DEPLOY_TEAM_MEMBERSHIP}" = "active" ]]; then
            curl -s \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${WEBHOOK_TOKEN}" \
              -d "{\"environment\": \"${ENVIRONMENT}\", \"repoName\": \"${REPO_NAME}\", \"imageTag\": \"${IMAGE_TAG}\", \"manualDeploy\": \"${MANUAL_DEPLOY}\"}" \
              "${WEBHOOK_URL}"
          else
            echo '::error title="Insufficient permissions to deploy"::The user needs to be a member of the GOV.UK Production Deploy GitHub team to deploy.'
            exit 1
          fi
