# USAGE
# -----
#
# on:
#   workflow_dispatch:
#     branches:
#       - main
#   push:
#     branches:
#       - main
#     paths-ignore:
#       - "Jenkinsfile"
#       - ".git**"
#
# jobs:
#   deploy-to-eks:
#     uses: alphagov/govuk-infrastructure/.github/workflows/deploy.yaml@main
#     secrets:
#       WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
#       WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

# REUSABLE WORKFLOW
# -----------------

name: Deploy

on:
  workflow_call:
    inputs:
      imageTag:
        description: 'An image tag to deploy'
        required: false
        default: ${{ github.sha }}
        type: string
      manualDeploy:
        description: 'Whether it is a manual deployment'
        required: false
        default: "false"
        type: string
      appName:
        description: 'Name of the app being deployed'
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'integration'
        type: string
    secrets:
      WEBHOOK_TOKEN:
        required: true
      WEBHOOK_URL:
        required: true

jobs:
  update-image-tag:
    name: Update image tag
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          IMAGE_TAG: ${{ inputs.imageTag }}
          REPO_NAME: ${{ inputs.appName }}
          MANUAL_DEPLOY: ${{ inputs.manualDeploy }}
          WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${WEBHOOK_TOKEN}" \
            -d "{\"environment\": \"${ENVIRONMENT}\", \"repoName\": \"${REPO_NAME}\", \"imageTag\": \"${IMAGE_TAG}\", \"manualDeploy\": \"${MANUAL_DEPLOY}\"}" \
            "${WEBHOOK_URL}"
