name: Build and publish signon-resources image to ECR

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "lib/**"
      - "Gemfile"
      - "Rakefile"
      - ".ruby-version"

jobs:
  build-publish-image-to-ecr:
    uses: alphagov/govuk-infrastructure/.github/workflows/ci-ecr.yaml@main
    with:
      ecr_repository_name: signon-resources
      additional_build_args: "-f docker/images/signon-resources/Dockerfile"
    secrets:
      AWS_GOVUK_ECR_ACCESS_KEY_ID: ${{ secrets.AWS_GOVUK_ECR_ACCESS_KEY_ID }}
      AWS_GOVUK_ECR_SECRET_ACCESS_KEY: ${{ secrets.AWS_GOVUK_ECR_SECRET_ACCESS_KEY }}
  trigger-deploy-to-integration:
    name: Trigger deploy to integration
    needs: build-and-publish-image
    uses: alphagov/govuk-infrastructure/.github/workflows/deploy.yaml@main
    secrets:
      WEBHOOK_TOKEN: ${{ secrets.ARGO_EVENTS_WEBHOOK_TOKEN }}
      WEBHOOK_URL: ${{ secrets.ARGO_EVENTS_WEBHOOK_URL }}
